# Generated by Django 3.2 on 2021-05-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'carEngine',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('Used', 'Used'), ('New ', 'New'), ('', 'What is the car status')], default='', max_length=10)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=9)),
                ('car_image1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('car_image2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('car_image3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('car_type', models.CharField(max_length=20)),
                ('car_description', models.TextField(blank=True, null=True)),
                ('manufacturing_date', models.DateField()),
                ('offer_type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('', 'Choose An Offer Type')], default='', max_length=10)),
                ('maintenance', models.TextField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('', 'Select Transmission')], default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sponsored', models.DateTimeField(auto_now=True)),
                ('featured', models.DateTimeField(auto_now=True)),
                ('approve', models.BooleanField(default=False)),
                ('car_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='DealerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17)),
                ('website', models.URLField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('biography', models.TextField()),
                ('address', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
            ],
            options={
                'verbose_name_plural': 'DealerInfo',
            },
        ),
        migrations.CreateModel(
            name='ContactDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.location')),
            ],
            options={
                'verbose_name_plural': 'ContactDealer',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cars.cars')),
            ],
            options={
                'verbose_name_plural': 'carType',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_location', to='Cars.location'),
        ),
        migrations.AddField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='Cars.brands'),
        ),
    ]
