# Generated by Django 3.1.1 on 2021-07-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Automobile', 'Automobile'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Health', 'Health'), ('', 'Select category')], default='', max_length=100)),
                ('content', models.TextField(verbose_name='Content')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Car_Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Car Engine',
            },
        ),
        migrations.CreateModel(
            name='Car_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Car Type',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Dealer_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17)),
                ('website', models.URLField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('biography', models.TextField()),
                ('address', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
            ],
            options={
                'verbose_name_plural': 'Dealer Info',
            },
        ),
        migrations.CreateModel(
            name='Contact_Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=200)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.location')),
            ],
            options={
                'verbose_name_plural': 'Contact Dealer',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(verbose_name='Content')),
                ('time', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Cars.blog')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('Foreign Used', 'Foreign Used'), ('New', 'New'), ('', 'What is the car status')], default='', max_length=15)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=9)),
                ('old_prize', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('car_image1', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('car_image2', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('car_image3', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('car_description', models.TextField(blank=True, null=True)),
                ('manufacturing_date', models.DateField()),
                ('offer_type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('', 'Choose An Offer Type')], default='', max_length=10)),
                ('maintenance', models.TextField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('', 'Select Transmission')], default='', max_length=20)),
                ('milleage', models.CharField(max_length=20)),
                ('first_registration', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField(default=False)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_location', to='Cars.location')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='Cars.brands')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type', to='Cars.car_type')),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
    ]
