# Generated by Django 3.1.1 on 2021-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_type',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=26062021),
            preserve_default=False,
        ),
    ]
