# Generated by Django 3.2 on 2021-05-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
    ]
