# Generated by Django 3.1.1 on 2021-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='old_prize',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
