# Generated by Django 3.2 on 2021-05-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdealer',
            old_name='agent_id',
            new_name='dealer_id',
        ),
    ]
