# Generated by Django 3.1.1 on 2021-05-11 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cars', '0002_cars_old_prize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarEngine',
            new_name='Car_Engine',
        ),
        migrations.RenameModel(
            old_name='CarType',
            new_name='Car_Type',
        ),
        migrations.RenameModel(
            old_name='ContactDealer',
            new_name='Contact_Dealer',
        ),
        migrations.RenameModel(
            old_name='DealerInfo',
            new_name='Dealer_Info',
        ),
        migrations.AlterModelOptions(
            name='car_engine',
            options={'verbose_name_plural': 'car_Engine'},
        ),
        migrations.AlterModelOptions(
            name='car_type',
            options={'verbose_name_plural': 'car_Type'},
        ),
        migrations.AlterModelOptions(
            name='contact_dealer',
            options={'verbose_name_plural': 'Contact_Dealer'},
        ),
        migrations.AlterModelOptions(
            name='dealer_info',
            options={'verbose_name_plural': 'Dealer Info'},
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='car_type',
            new_name='car_types',
        ),
    ]
