# Generated by Django 3.2 on 2021-05-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_rename_agent_id_contactdealer_dealer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='dealerinfo',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile'),
        ),
    ]
