# Generated by Django 3.1.1 on 2021-07-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
    ]
