# Generated by Django 3.2.3 on 2021-07-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brands'},
        ),
    ]
