# Generated by Django 3.2 on 2021-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_auto_20210511_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(max_length=200),
        ),
    ]
