# Generated by Django 3.1.1 on 2021-05-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_auto_20210511_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_type',
            options={'verbose_name_plural': 'car Type'},
        ),
    ]
