# Generated by Django 3.1.1 on 2021-08-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_alter_brands_options'),
        ('Cars', '0004_auto_20210718_2027'),
    ]

    operations = [
    ]
