# Generated by Django 3.2 on 2021-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Automobile', 'Automobile'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Health', 'Health'), ('', 'Select category')], default='', max_length=100),
        ),
    ]
