# Generated by Django 3.1.1 on 2021-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='car_type',
            name='names',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cars',
            name='status',
            field=models.CharField(choices=[('Foreign Used', 'Foreign Used'), ('New', 'New'), ('', 'What is the car status')], default='', max_length=15),
        ),
    ]
