# Generated by Django 3.1.1 on 2021-05-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_auto_20210511_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_engine',
            options={'verbose_name_plural': 'Car Engine'},
        ),
        migrations.AlterModelOptions(
            name='car_type',
            options={'verbose_name_plural': 'Car Type'},
        ),
    ]
