# Generated by Django 3.2 on 2021-06-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_auto_20210602_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
    ]
