# Generated by Django 3.1.1 on 2021-05-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_auto_20210511_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_type',
            name='Type',
            field=models.OneToOneField(choices=[('Sedan', 'Sedan (car)'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sport Car', 'Sport Car'), ('MVP', 'MVP'), ('', 'Select An Engine Type')], default='', on_delete=django.db.models.deletion.CASCADE, to='Cars.cars'),
        ),
    ]
