# Generated by Django 3.1.1 on 2021-05-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_auto_20210511_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_type',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_types',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_engine',
            field=models.ForeignKey(default=15052021, on_delete=django.db.models.deletion.CASCADE, related_name='car_engine', to='Cars.car_engine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(default=15052021, on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='Cars.car_type'),
            preserve_default=False,
        ),
    ]
