# Generated by Django 3.2 on 2021-05-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0009_alter_cars_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='image',
        ),
    ]
