# Generated by Django 3.2 on 2021-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0010_remove_brands_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_type',
            name='Type',
        ),
        migrations.AddField(
            model_name='car_type',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan (car)'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sport Car', 'Sport Car'), ('MVP', 'MVP'), ('', 'Select An Car Type')], default='', max_length=30),
        ),
    ]
